#!/bin/bash
# Interactive script to generate chezmoi.toml
# Usage: ~/.local/share/chezmoi/setup-config.sh

set -e

CONFIG_DIR="$HOME/.config/chezmoi"
CONFIG_FILE="$CONFIG_DIR/chezmoi.toml"
TEMPLATE_FILE="$HOME/.local/share/chezmoi/chezmoi.toml.template"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}=== Chezmoi Configuration Setup ===${NC}"
echo ""

# Create config directory
mkdir -p "$CONFIG_DIR"

# Check if template exists
if [[ ! -f "$TEMPLATE_FILE" ]]; then
    echo -e "${YELLOW}Creating template file...${NC}"
    cat > "$TEMPLATE_FILE" << 'EOF'
# Chezmoi local configuration template
# This file is auto-generated by setup-config.sh
# DO NOT edit this file directly - edit the generated chezmoi.toml instead

[data.anthropic]
# Your Anthropic API token for Claude
# Get from: https://console.anthropic.com/settings/keys
token = ""

[data.github]
# GitHub personal access token (optional)
# Get from: https://github.com/settings/tokens
token = ""

[data.openai]
# OpenAI API key (optional)
# Get from: https://platform.openai.com/api-keys
apikey = ""

# Add other service tokens as needed
# [data.servicename]
# token = "your_token"
EOF
fi

# Check if config already exists
if [[ -f "$CONFIG_FILE" ]]; then
    echo -e "${YELLOW}Config file already exists: $CONFIG_FILE${NC}"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

# Copy template to config
cp "$TEMPLATE_FILE" "$CONFIG_FILE"

echo ""
echo "Please enter your API tokens (press Enter to skip):"
echo "----------------------------------------"

# Prompt for Anthropic token
echo ""
read -p "Anthropic API token (for Claude): " anthropic_token
if [[ -n "$anthropic_token" ]]; then
    sed -i '' "s|^token = \"\"$|token = \"$anthropic_token\"|" "$CONFIG_FILE"
    echo -e "${GREEN}✓ Anthropic token saved${NC}"
fi

# Prompt for GitHub token
echo ""
read -p "GitHub personal access token (optional): " github_token
if [[ -n "$github_token" ]]; then
    sed -i '' "s|^token = \"\"$|token = \"$github_token\"|" "$CONFIG_FILE"
    echo -e "${GREEN}✓ GitHub token saved${NC}"
fi

# Prompt for OpenAI key
echo ""
read -p "OpenAI API key (optional): " openai_key
if [[ -n "$openai_key" ]]; then
    sed -i '' "s|^apikey = \"\"$|apikey = \"$openai_key\"|" "$CONFIG_FILE"
    echo -e "${GREEN}✓ OpenAI key saved${NC}"
fi

echo ""
echo -e "${GREEN}=== Configuration Complete ===${NC}"
echo "Config file created at: $CONFIG_FILE"
echo ""
echo "Current config:"
cat "$CONFIG_FILE"
echo ""
echo "You can edit it later with: vim $CONFIG_FILE"
